### ISSUE TITLE
tabpbem_file error (fixed)

### ISSUE THREAD

**Issue by abenjak** [cibiobcg/abemus#1]
Hello,
The function `callsnvs` threw this error:
```
Error in fread(input = tabpbem_file, stringsAsFactors = FALSE, showProgress = FALSE,  : 
 input= must be a single character string containing a file name, a system command containing at least one space, a URL starting 'http[s]://', 'ftp[s]://' or 'file://', or, the input data itself containing at least one \n or \r
```
The problem is caused by `filter.R` at line 108. Instead of 
`tabpbem_file = list.files(pbem_dir, pattern = paste0('bperr',chrom,'.tsv'),full.names = TRUE)
`
it should be
`tabpbem_file = list.files(pbem_dir, pattern = paste0('bperr_chr',chrom,'.tsv'),full.names = TRUE)
`

The fix makes the function look for a file like `bperr_chr1.tsv` instead of `bperr_1.tsv`.

Kind regards,
Andrej
PS: I used `hg38` as reference. I don't know how the files in `outdir.bperr.name` get named when using `hg19`.

**Comment by DavidAustinNix** [comment]
Same issue.  Until this fix gets built into the package, one can copy and rename the BaseErrorModel/bperr_xxx.tsv files, e.g. 'cp bperr_chr1.tsv bperr_1.tsv'

**Comment by ncasiraghi** [comment]
Thank you for pointing this out. Now all output files do not have `chr` prefix in their name.
