### ISSUE TITLE
Test example doesn't generate the pmtab_F3_optimalR_TUMOR tsv files?

### ISSUE THREAD

**Issue by DavidAustinNix** [cibiobcg/abemus#4]
Just working through test_example.R with R/4.0.2.  Final steps to apply the pbem scaling factor to calls, doesn't output the optimalR tsv files?  After calling the apply_scaling_factor(xxx) method, does one need to do something else?  When heading the calls, e.g. head( calls$tabsnvs_index_scalfact ) the file paths are in the table but don't actually exist, see below. Any suggestions? Thanks

> head( calls$tabsnvs_index_scalfact )
  patient  plasma germline
1    PT01 TUMOR_A   CTRL_A
2    PT01 TUMOR_B   CTRL_B
3    PT02 TUMOR_C   CTRL_C
5    PT04 TUMOR_E     <NA>
                                                                                                                   tabcalls_f1
1 /uufs/chpc.utah.edu/common/HIPAA/u0028003/Scratch/Underhill/Abemus/test_dataset_abemus//Results/TUMOR_A/pmtab_F1_TUMOR_A.tsv
2 /uufs/chpc.utah.edu/common/HIPAA/u0028003/Scratch/Underhill/Abemus/test_dataset_abemus//Results/TUMOR_B/pmtab_F1_TUMOR_B.tsv
3 /uufs/chpc.utah.edu/common/HIPAA/u0028003/Scratch/Underhill/Abemus/test_dataset_abemus//Results/TUMOR_C/pmtab_F1_TUMOR_C.tsv
5 /uufs/chpc.utah.edu/common/HIPAA/u0028003/Scratch/Underhill/Abemus/test_dataset_abemus//Results/TUMOR_E/pmtab_F1_TUMOR_E.tsv
                                                                                                                   tabcalls_f2
1 /uufs/chpc.utah.edu/common/HIPAA/u0028003/Scratch/Underhill/Abemus/test_dataset_abemus//Results/TUMOR_A/pmtab_F2_TUMOR_A.tsv
2 /uufs/chpc.utah.edu/common/HIPAA/u0028003/Scratch/Underhill/Abemus/test_dataset_abemus//Results/TUMOR_B/pmtab_F2_TUMOR_B.tsv
3 /uufs/chpc.utah.edu/common/HIPAA/u0028003/Scratch/Underhill/Abemus/test_dataset_abemus//Results/TUMOR_C/pmtab_F2_TUMOR_C.tsv
5 /uufs/chpc.utah.edu/common/HIPAA/u0028003/Scratch/Underhill/Abemus/test_dataset_abemus//Results/TUMOR_E/pmtab_F2_TUMOR_E.tsv
                                                                                                                   tabcalls_f3
1 /uufs/chpc.utah.edu/common/HIPAA/u0028003/Scratch/Underhill/Abemus/test_dataset_abemus//Results/TUMOR_A/pmtab_F3_TUMOR_A.tsv
2 /uufs/chpc.utah.edu/common/HIPAA/u0028003/Scratch/Underhill/Abemus/test_dataset_abemus//Results/TUMOR_B/pmtab_F3_TUMOR_B.tsv
3 /uufs/chpc.utah.edu/common/HIPAA/u0028003/Scratch/Underhill/Abemus/test_dataset_abemus//Results/TUMOR_C/pmtab_F3_TUMOR_C.tsv
5 /uufs/chpc.utah.edu/common/HIPAA/u0028003/Scratch/Underhill/Abemus/test_dataset_abemus//Results/TUMOR_E/pmtab_F3_TUMOR_E.tsv
  case_mean_coverage
1           2286.657
2           2293.896
3           2285.669
5           2292.059
                                                                                                                   tabcalls_f3_optimalR
1 /uufs/chpc.utah.edu/common/HIPAA/u0028003/Scratch/Underhill/Abemus/test_dataset_abemus//Results/TUMOR_A/pmtab_F3_optimalR_TUMOR_A.tsv
2 /uufs/chpc.utah.edu/common/HIPAA/u0028003/Scratch/Underhill/Abemus/test_dataset_abemus//Results/TUMOR_B/pmtab_F3_optimalR_TUMOR_B.tsv
3 /uufs/chpc.utah.edu/common/HIPAA/u0028003/Scratch/Underhill/Abemus/test_dataset_abemus//Results/TUMOR_C/pmtab_F3_optimalR_TUMOR_C.tsv
5 /uufs/chpc.utah.edu/common/HIPAA/u0028003/Scratch/Underhill/Abemus/test_dataset_abemus//Results/TUMOR_E/pmtab_F3_optimalR_TUMOR_E.tsv
  tabcalls_f3_optimalR_used
1                       1.1
2                       1.1
3                       1.1
5                       1.1

**Comment by ncasiraghi** [comment]
Hi David, thanks for pointing this out. I fixed the code and now it write output tables.
