### ISSUE TITLE
apply_scaling_factor with use.optimal.R = TRUE error when target_Mbp=4.40 and mean_coverage=200 since 2 possibilities for Ropt (1,2 and 1,4)

### ISSUE THREAD

**Issue by hanaecarrie** [cibiobcg/abemus#6]
Dear authors, I am encountering an issue while applying apply_scaling_factor with use.optimal.R = TRUE in ABEMUS. The error appears on most samples but not systematically. I manage to get the _optimalR_.tsv file for a few samples.
 
I get the following error:
in line 61 of apply_scaling_factor: tabindex[i,paste0("tabcalls_f3","_optimalR_used")] <- optR
Error in `[<-.data.frame`(`*tmp*`, i, paste0("tabcalls_f3", "_optimalR_used"),  : 
  replacement has 2 rows, data has 1

This is due to the fact that I get 2 Ropt values instead of a single in those failing cases.
This looks like this is due to the fact tab_optimal_R has 2 entries for target_Mbp=4.40 and mean_coverage=200 (row ID 15 and 17). **Why is that?**

**How to solve this issue?
Shall we remove this double option of scaling factor in tab_optimal_R?**

Many thanks in advance for your help,
Kind regards,
Hanaé

> tab_optimal_R
   target_Mbp mean_coverage scalingfactor
6        0.04           200           1.1
7        0.04           500           1.1
8        0.04          1000           1.1
5        0.04          2000           1.1
10       0.20           200           1.2
11       0.20           500           1.1
12       0.20          1000           1.1
9        0.20          2000           1.2
18       0.40           200           1.2
19       0.40           500           1.1
20       0.40          1000           1.1
13       0.40          2000           1.2
26       1.10           200           1.2
27       1.10           500           1.1
28       1.10          1000           1.1
25       1.10          2000           1.2
34       2.10           200           1.2
35       2.10           500           1.1
36       2.10          1000           1.1
33       2.10          2000           1.1
**15       4.40           200           1.4
17       4.40           200           1.2**
16       4.40           500           1.1
14       4.40          2000           1.1
22       8.90           200           2.2
23       8.90           500           1.2
24       8.90          1000           1.3
21       8.90          2000           1.2
30      17.70           200           2.2
31      17.70           500           1.3
32      17.70          1000           1.4
29      17.70          2000           1.3
38      26.60           200           2.2
39      26.60           500           1.5
40      26.60          1000           1.4
37      26.60          2000           1.3
2       36.00           200           2.2
3       36.00           500           2.2
4       36.00          1000           1.4
1       36.00          2000           1.4

Please find below an example of the values of my variables used at this point of the function:

> target_size
[1] 4.995

> sizes
 [1]  0.04  0.20  0.40  1.10  2.10  4.40  8.90 17.70 26.60 36.00

> closest_target_size
[1] 4.4

> bombanel
   target_Mbp mean_coverage scalingfactor
15        4.4           200           1.4
17        4.4           200           1.2
16        4.4           500           1.1
14        4.4          2000           1.1

> covs
[1]  200  200  500 2000

> closest_coverage
[1] 200 200

> optR
[1] 1.4 1.2

**Comment by ncasiraghi** [comment]
Dear Hanaé, thank you for your interest in abemus. We corrected the tab_optimal_R object.
Please, reinstall abemus from github to get the fixed version.
